let productos = [
    {
        id: 1,
        name: 'Chocolate Blanco Oreo',
        marca: 'Milka',
        precio: '70',
        categoria: 'blanco',
        presentacion: "20 gr",
        img: "https://i.ibb.co/8sftFMS/oreo-blanco.png",
        stock: 10,
    },
    {
        id: 2,
        name: 'Cofler Block',
        marca: 'Arcor',
        precio: '160',
        categoria: 'conleche',
        presentacion: "90 gr",
        img: "https://i.ibb.co/bB8HrKT/block.jpg",
        stock: 10,
    },
    {
        id: 3,
        name: 'Kinder Bueno',
        marca: 'Kinder',
        precio: '130',
        categoria: 'rellenos',
        presentacion: "43 gr",
        img: "https://i.ibb.co/8DXrcqg/kb.webp",
        stock: 10,
    },
    {
        id: 4,
        name: 'Chocolate con Almendras',
        marca: 'Lindt',
        precio: '1500',
        categoria: 'conleche',
        presentacion: "300 gr",
        img: "https://i.ibb.co/3fBH65t/lindt-swiss-premium-leche-almendras-300g.png",
        stock: 10,
    },
    {
        id: 5,
        name: 'Yogurth Frutilla',
        marca: 'Cadbury',
        precio: '100',
        categoria: 'relleno',
        presentacion: "29 gr",
        img: "https://i.ibb.co/f2jvJzw/cadyog.webp",
        stock: 10,
    },
    {
        id: 6,
        name: 'Chocolate 70% Cacao',
        marca: 'Aguila',
        precio: '470',
        categoria: 'amargo',
        presentacion: "150 gr",
        img: "https://i.ibb.co/LJk40Ct/aguila.jpg",
        stock: 10,
    },
    {
        id: 7,
        name: 'Cofler Dulce de Leche',
        marca: 'Arcor',
        precio: '72',
        categoria: 'rellenos',
        presentacion: "42 gr",
        img: "https://i.ibb.co/prhbnQN/cof-ddl.webp",
        stock: 10,
    },
    {
        id: 8,
        name: 'Intense',
        marca: 'Cadbury',
        precio: '140',
        categoria: 'amargo',
        presentacion: "24 gr",
        img: "https://i.ibb.co/w4DRvW1/cad-int.jpg",
        stock: 10,
    },

];

export default productos;
